import './globals.css';

import { Inter } from 'next/font/google';

const inter = Inter({
    subsets: ['latin'],
    variable: '--font-inter',
});

export const metadata = {
    title: 'Create Next App',
    description: 'Generated by create next app',
};

export default function RootLayout({ children }) {
    return (
        <html lang="en" className={`${inter.variable} h-full antialiased`}>
            <body className="flex min-h-screen w-full flex-col bg-[#0F1515] text-white">
                {children}
            </body>
        </html>
    );
}
